### ISSUE TITLE
nats sub --stream does not respect the context JS domain

### ISSUE THREAD

**Issue by Zambito1** [nats-io/natscli#1244]
### Observed behavior

This is similar to #1073, but instead of specifying the JS domain with the `--js-domain` command line argument, the JS domain from the currently selected context is not respected. `nats sub --stream` will always use the JS domain of the server that the client is connected to, unless otherwise specified with `--js-domain`. 

### Expected behavior

When using a context that specifies a JS domain, that JS domain should be used by `nats sub`. `nats --context foo sub --stream bar [...]` should use the JS domain specified in `foo` if there is one, and only use the JS domain of the server that the client is connecting to if one is not otherwise specified in the context.

### Server and client version

Server: `2.10.24`

Client: `v0.1.2-0.20250109120435-65a2f00845a5` (recently installed from `main`)

### Host environment

Running the official Docker containers on a 64 bit GNU/Linux machine.

### Steps to reproduce

* Create two NATS servers
* Put them each in different JS domains, and establish a leaf connection between the two
* Create different stream (with a different name to make it obvious) on each server
* Use `nats ctx add`, `nats ctx edit`, and `nats ctx select` to create a context that connects to server A, and uses the JS domain of server B.
* Use `nats sub --stream SERVER_B_STREAM` and observe that it will fail with a `context deadline exceeded` error.
* Use `nats sub --stream SERVER_A_STREAM` and observe that it will succeed, even though that stream does not exist in the domain of the selected context.

**Comment by ripienaar** [comment]
This one should already be fixed in main, please check there.

**Comment by Zambito1** [comment]
@ripienaar Still seeing the issue on `v0.1.2-0.20250121111352-e105ef6dd240`.

**Comment by ripienaar** [comment]
Ah, I see the fix for this was actually broken, if possible can you see if this helps?

```patch
diff --git a/cli/util.go b/cli/util.go
index e0ea270..1549972 100644
--- a/cli/util.go
+++ b/cli/util.go
@@ -315,8 +315,8 @@ func natsOpts() []nats.Option {
 func jsOpts() []nats.JSOpt {
 	opts := opts()
 	jso := []nats.JSOpt{
-		nats.Domain(opts.JsDomain),
-		nats.APIPrefix(opts.JsApiPrefix),
+		nats.Domain(opts.Config.JSDomain()),
+		nats.APIPrefix(opts.Config.JSAPIPrefix()),
 		nats.MaxWait(opts.Timeout),
 	}
 
```

**Comment by Zambito1** [comment]
That seems to have fixed it! I didn't do complete testing of other possible cases, but I did test that it does use the JS domain from the context at least.

**Comment by ripienaar** [comment]
Done in https://github.com/nats-io/natscli/pull/1246
